import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Tester Automation",
    company: "Tma Solutions",
    logo: "/images/careers/TMA-Solutions-Logo.png",
    location: "Hồ Chí mình, Viet Nam 🇻🇳",
    location_type: "Onsite",
    type: "Full-time employee",
    start_date: "2021-06",
    end_date: "2023-06",
    industry: "Software Development",
    link: "https://www.tmasolutions.vn/",
    responsibilities: [
      "Designed, developed, and maintained automated test scripts to ensure software quality and stability.",
      "Executed regression, functional, and performance tests using automation frameworks and tools.",
      "Collaborated with frontend and backend teams to identify, report, and resolve defects, ensuring smooth user experience.",
      "Participated in test planning and contributed to continuous improvement of QA processes."
    ],
    isShow: true,
  },
  {
    position: "Frontend Web Developer",
    company: "Tma Solutions",
    logo: "/images/careers/TMA-Solutions-Logo.png",
    location: "Hồ Chí mình, Viet Nam 🇻🇳",
    location_type: "Onsite",
    type: "Full-time employee",
    start_date: "2023-06",
    end_date: null,
    industry: "Software Development",
    link: "https://www.tmasolutions.vn/",
    responsibilities: [
      "Developed responsive and interactive web applications using Angular and React to deliver high-quality software products for customers.",
      "Implemented reusable UI components, optimized performance, and ensured cross-browser compatibility.",
      "Collaborated closely with backend, design, and product teams to align features with customer requirements and ensure seamless user experience.",
      "Participated in code reviews and contributed to continuous improvement of frontend development processes."
    ],
    isShow: true,
  },
  // {
  //   position: "Head of Technology in the Research and Technology Division",
  //   company:
  //     "Himpunan Mahasiswa Sistem Informasi Universitas Jambi (HIMASI UNJA)",
  //   logo: "/images/careers/himasi-unja.jpeg",
  //   location: "Jambi, Indonesia 🇮🇩",
  //   location_type: "Onsite",
  //   type: "Part-time",
  //   start_date: "2024-12",
  //   end_date: null,
  //   industry: "school",
  //   link: "https://himasi.unja.ac.id/",
  //   responsibilities: [
  //     "Led the development of an internal RFID-based attendance system for HIMASI UNJA.",
  //     "Managed the technical team and oversaw the implementation of hardware-software integration.",
  //     "Ensured the system was user-friendly, secure, and met the organization's operational needs.",
  //   ],
  //   isShow: true,
  // },
  // {
  //   position: "Mobile Development Cohort",
  //   company: "Bangkit Academy led by Google, Tokopedia, Gojek & Traveloka",
  //   logo: "/images/careers/bangkit.png",
  //   location: "Bandung, Indonesia 🇮🇩",
  //   location_type: "Remote",
  //   type: "Part-time",
  //   start_date: "2024-9",
  //   end_date: "2024-12",
  //   industry: "school",
  //   link: "https://himasi.unja.ac.id/",
  //   responsibilities: [
  //     "Mastered Android development using Kotlin, Jetpack Components, and modern tools like Room Database and DataStore for state and data management.",
  //     "Gained hands-on experience with ViewModel, RecyclerView, and Hilt for dependency injection to create robust and scalable mobile applications.",
  //     "Collaborated with a cross-functional team to develop a Company-Based Capstone Project, applying Agile methodologies and real-world problem-solving.",
  //     "Enhanced teamwork, problem-solving, and communication skills in a multicultural environment.",
  //   ],
  //   isShow: true,
  // },
  // {
  //   position: "Mobile Developer",
  //   company: "Pt. Amanah Karya Indonesia (Amanah Corp)",
  //   logo: "/images/careers/amanah-karya-indonesia.jpeg",
  //   location: "Depok, Indonesia 🇮🇩",
  //   location_type: "Remote",
  //   type: "Part-time",
  //   start_date: "2024-10",
  //   end_date: "2024-12",
  //   industry: "school",
  //   link: "https://amanahcorp.co.id/",
  //   responsibilities: [
  //     "Designed and developed a mobile application using Kotlin, incorporating Room Database, Hilt, and ViewModel for optimal performance and scalability.",
  //     "Implemented secure and user-friendly features tailored to the berbagi.link platform to improve user engagement and accessibility.",
  //     "Worked closely with PT Amanah Corp to ensure alignment with business objectives and deliver impactful, real-world solutions.",
  //     "Strengthened technical and soft skills, including problem-solving, teamwork, and communication, in a professional, multicultural setting.",
  //   ],
  //   isShow: true,
  // },
];
