export const METADATA = {
  creator: "Nguyễn Thành Trung",
  description: "Experienced Fullstack Developer specializing in Angular, React, Next.js, TypeScript, and Automation Testing.",
  keyword: [
    'Nguyễn Thành Trung',
    'nttrung',
    'Fullstack Developer',
    'Frontend Developer',
    'React Developer',
    'Next.js Developer',
    'Automation Tester',
    'Web Developer Vietnam',
    'Portfolio',
    'Angular Developer',
    'nttrung developer',
  ],
  authors: {
    name: "nttrung",
    url: process.env.DOMAIN,
  },
  openGraph: {
    url: process.env.DOMAIN,
    siteName: "nttrung",
    locale: "vi-VI",
    title: 'Nguyễn Thành Trung | Fullstack Developer & Automation Tester | Personal Website',
    description: 'Experienced Fullstack Developer specializing in Angular, React, Next.js, TypeScript, and Automation Testing.',
  },
  exTitle: "| nttrung",
  profile: "/images/nttrung-avatar.jpg",
};
